
services:
  database:
    image: postgres:latest
    container_name: songspec-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: song-spec-db
    ports:
      - "5432:5432"
